on:
  schedule:
    - cron: '0 2 * * *'  # UTCの2:00（JSTの11:00）に毎日実行する

jobs:
  collect-and-send-news:
    runs-on: ubuntu-latest
    name: Collect news and send to my slack
    steps:
      - name: Collect news
        uses: hirakawamizuki/collect-daily-news-action@v0.1.2  # ニュースを収集するための自作アクション
        id: collect-news
        with: 
          keywords: "Docker,GitHub+Actions,GitHub+Container+Registry,Docker+Hub,Amazon+ECR,CentOS+終了,アジャイル"
          how-many-days: "1"  # 過去1日分のニュースを収集
          output-format: "mrkdwn"  # slack mrkdwn形式で出力
      - name: Send to my slack
        uses: tokorom/action-slack-incoming-webhook@main  # Marketplaceで見つけたSlack通知用のアクション
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ${{ steps.collect-news.outputs.result }}  # アクション間でアウトプットを受け渡している
